### ISSUE TITLE
pip install circleci-helpers not working

### ISSUE THREAD

**Issue by andrewrothstein** [dennybaa/circleci-helpers#1]
(foo)drew ~ > pip install circleci-helpers
Downloading/unpacking circleci-helpers
  Downloading circleci-helpers-0.1.1.tar.gz
  Running setup.py (path:/Users/drew/foo/build/circleci-helpers/setup.py) egg_info for package circleci-helpers
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/drew/foo/build/circleci-helpers/setup.py", line 11, in <module>
        install_reqs, dep_links = fetch_requirements(REQUIREMENTS_FILE)
      File "dist_utils.py", line 34, in fetch_requirements
        if req.link:
    AttributeError: 'InstallRequirement' object has no attribute 'link'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/drew/foo/build/circleci-helpers/setup.py", line 11, in <module>

    install_reqs, dep_links = fetch_requirements(REQUIREMENTS_FILE)

  File "dist_utils.py", line 34, in fetch_requirements

    if req.link:

AttributeError: 'InstallRequirement' object has no attribute 'link'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/drew/foo/build/circleci-helpers
Storing debug log for failure in /Users/drew/.pip/pip.log
(foo)drew ~ >

**Comment by dennybaa** [comment]
@andrewrothstein Hey, Andrew. I think you are using outdated pip.

Here how it works with *pip 8.1.2*

```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip.req
>>> r1 = pip.req.InstallRequirement.from_line('git+https://host/pkg6@branch#egg=pkg6-1.6')
>>> r1.link
<Link git+https://host/pkg6@branch#egg=pkg6-1.6>
>>> r2 = pip.req.InstallRequirement.from_line('docopt')
>>> r2.link
>>> 
```

**Comment by andrewrothstein** [comment]
worked! thanks! do you want me to raise a pull request against the docs? the baseline recommendation doesn't include a 'sudo -H pip install --upgrade pip' before the 'sudo -H pip install circlci-helpers'.

**Comment by dennybaa** [comment]
@andrewrothstein :+1:

**Comment by dennybaa** [comment]
@andrewrothstein Yeah, why not, you can just mention that version should be definitely **>= 6.0.0**, which actually was released on Dec 22, 2014 !

**Comment by andrewrothstein** [comment]
https://github.com/dennybaa/circleci-helpers/pull/2

**Comment by doomroep5** [comment]
> (foo)drew ~ > pip install circleci-helpers Downloading/unpacking circleci-helpers Downloading circleci-helpers-0.1.1.tar.gz Running setup.py (path:/Users/drew/foo/build/circleci-helpers/setup.py) egg_info for package circleci-helpers Traceback (most recent call last): File "", line 17, in File "/Users/drew/foo/build/circleci-helpers/setup.py", line 11, in install_reqs, dep_links = fetch_requirements(REQUIREMENTS_FILE) File "dist_utils.py", line 34, in fetch_requirements if req.link: AttributeError: 'InstallRequirement' object has no attribute 'link' Complete output from command python setup.py egg_info: Traceback (most recent call last):
> 
> File "", line 17, in
> 
> File "/Users/drew/foo/build/circleci-helpers/setup.py", line 11, in
> 
> ```
> install_reqs, dep_links = fetch_requirements(REQUIREMENTS_FILE)
> ```
> 
> File "dist_utils.py", line 34, in fetch_requirements
> 
> ```
> if req.link:
> ```
> 
> AttributeError: 'InstallRequirement' object has no attribute 'link'
> 
> Cleaning up... Command python setup.py egg_info failed with error code 1 in /Users/drew/foo/build/circleci-helpers Storing debug log for failure in /Users/drew/.pip/pip.log (foo)drew ~ >
